version: '3'
services:
  nextjs-app:
    image: node:18-alpine
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
    command: "yarn start"
