import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const clash = localfont({
	src: [
		{
			path: "../../public/fonts/ClashDisplay-Bold.ttf",
		},
	],
	variable: "--font-clash",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${clash.variable}`}>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
