name: Build um.me Portfolio
on:
  push:
    branches: 
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build


