name: Build um.me Portfolio
on:
  push:
    branches: 
      - prod
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: deployment-secrets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: myimage:latest
      - name: Inspect
        run: |
          docker image inspect myimage:latest  
      - name: Export 
        run: |
          docker save -o myimageLatest.tar myimage:latest
      - name: Showing Off 
        run: |
          ls
      - name: ip
        run: |
          echo ${{ vars.CONTABO_IP }}
      - name: Copy files to remote server
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          host: 31.220.89.68
          username: root
          password: ${{ secrets.CONTABO_PWD }}
          local: ./myimageLatest.tar
          remote: /root/myimageLatest.tar
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.CONTABO_SSH_PRIVATE }}
      - name: Run command on remote server
        run: |
          ssh root@31.220.89.68 'pwd'
         
            

