name: Build um.me Portfolio
on:
  push:
    branches: 
      - prod
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: deployment-secrets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: myimage:latest
      - name: Inspect
        run: |
          docker image inspect myimage:latest  
      - name: Export 
        run: |
          docker save -o myimageLatest.tar myimage:latest
      - name: Showing Off 
        run: |
          ls
      - name: copy
        uses: garygrossgarten/github-action-scp@v0.8.0
        with: 
          local: ./myimageLatest.tar
          remote: ${{ variables.CONTABO_IP }}
          username: root
          password: ${{ secrets.CONTABO_PWD }}
         
            

